runtime: python39
# you can use default bucket name which will be created by app engine
# or you can create your own bucket in the same project
env_variables:
  BUCKET_NAME: "<BUCKET NAME>" //here i would add busket name
